name: Convert PR to Draft if Missing Reviewers

on:
  pull_request:
    types:
      - opened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write  # Needed for GraphQL mutations

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Convert to Draft
        run: |
          REVIEWERS_COUNT=$(jq '.pull_request.requested_reviewers | length' "$GITHUB_EVENT_PATH")
          AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          REPO_NAME=$(jq -r '.repository.full_name' "$GITHUB_EVENT_PATH")

          if [ "$REVIEWERS_COUNT" -eq 0 ]; then
            echo "No reviewers assigned. Converting PR to draft..."

            # Get PR Node ID using GitHub GraphQL API
            PR_NODE_ID=$(curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.github+json" \
              --data '{"query": "query { repository(name: \"'${REPO_NAME#*/}'\", owner: \"'${REPO_NAME%/*}'\") { pullRequest(number: '${PR_NUMBER}') { id } } }"}' \
              https://api.github.com/graphql | jq -r '.data.repository.pullRequest.id')

            echo "PR Node ID: $PR_NODE_ID"

            # Convert PR to draft using GraphQL Mutation
            curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.github.v4+json" \
              --data '{"query": "mutation { convertPullRequestToDraft(input: {pullRequestId: \"'${PR_NODE_ID}'\"}) { pullRequest { id number isDraft } } }"}' \
              https://api.github.com/graphql

            # Add a comment to the PR
            gh pr comment "https://github.com/$REPO_NAME/pull/$PR_NUMBER" \
              --body ":warning: @${AUTHOR} please assign at least one reviewer before marking this PR as ready for review."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
