name: Terraform CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
        description: 'username for go mod init'
        default: 'alexplayer15'
      directory:
        required: true
        type: string
        description: 'directory for go mod init'
        default: 'terratest_poc'
      terraform_version: 
        required: true
        type: string
        description: 'terraform version to use'
        default: '1.6.0'


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.0' 

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-2'  

    - name: Terraform init
      run: |
        cd main
        terraform init

    # - name: Terraform validate
    #   run: |
    #     cd main
    #     terraform validate

    - name: Terraform plan 
      run: |
        cd main
        terraform plan

    - name: Install Terratest Dependencies
      run: |
        go mod init github.com/${{ inputs.username }}/${{ inputs.directory }}
        go mod tidy

    - name: Run Terratest
      run: |
        cd test
        go test -v -timeout 30m ./...

    # - name: Apply Terraform
    #   run: |
    #     cd main
    #     terraform apply --auto-approve
    
    # - name: Destroy Terraform 
    #   run: |
    #     cd main
    #      terraform destroy --auto-approve